spring:
  application:
    name: sueldo-microservice
  datasource:
    # url: jdbc:mysql://localhost:3306/mtisw2_sueldos
    # password: danielusach
    # username: root
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8085
  forward-headers-strategy: framework
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}



